TRUTH = (
    "As a kid, what was your most favorite color?'?",
    "Who was the last person you liked the most? in telegram Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What is your choice ? DATE,MARRY,KILL SHASHANK,DEADPOOL,ZEUS",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "What is the best Wi-Fi name you have seen in your entire life??",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s your least favorite memory from college and school?'",
    " What’s the grossest thing that you do alone?",
"What is your Wi-Fi password?",
" Which movie would you want it to be if your life was a movie?",
"Would you ever get plastic surgery?",
"Have you ever had a near-death experience?",
"What’s a skill you wish you had?",
 " What’s the first thing you wash in the shower??",
 "Who was the last person you said, “I love you” to?",
 " Do people drink or eat soup??",
"Have you ever broken someone’s heart?",
 "Have you ever peed in the shower?",
 "What’s the most bogus rumor you’ve ever heard about yourself?",
 "What’s the most bogus rumor you’ve ever spread or heard about someone else?",
" When and where was your first kiss? Who was it with?",
"Do you think cheating can ever be justified? How?",
"Have you ever thrown up in public?",
"When’s the last time you got rejected?",
"What’s the most common misconception about you?",
"Have you ever seriously injured another person?",
    "Do you love @itssmeZeus ?",
    "Do freestyle rap for 1 minute about the other participants.",
"Smell every other players’ armpits.",
"Kiss the person to your left.",
"Do an impression of another player until someone can figure out who it is.",
"Call your crush.",
"Dance with no music for 1 minute.",
"Do a cartwheel.",
"Let the person on your right draw on your face.",
"Give your phone to another player who can send one text saying anything they want to one of your contacts.",
" Drink lemon juice.",
"Crack an egg on our head.",
 "Swap clothes with someone of the opposite sex for 2 rounds.",
" Act like a chicken until your next turn.",
"Burp the alphabet.",
"Talk in a Jamaican accent until your next turn.",
"call a friend, pretend it’s their birthday, and sing “Happy Birthday” to them.",
"What’s your least favorite holiday?",
"Shower with your clothes on.",
"Take a selfie on the toilet and post it.",
"End each sentence with the word “not” until your next turn.",
"Name a famous person that looks like each player.",
"Dance like your life depends on it.",
"Eat a packet of hot sauce or ketchup straight.",
"Who is your favorite celebrity crush?.",
"Thanks Zeus ,shashank,samar,jay,manya,suraj,windflower,deadpool,watcher,Bhumi,himanshu,oreo,ayan,Vashishth,raini,sumita,mina,rim,.",
"Put on a blindfold and touch the other players’ faces until you can figure out who it is.",
"Let the other players redo your hairstyle.",
"Do you ever cry while watching an emotional film? or which movie",
" Let the player to your right redo your makeup.",
" Have you ever kissed someone at school?",
"What is your most favorite GIF?.",
 "Lick a bar of soap.",
"Eat a teaspoon of mustard.",
"Talk without closing your mouth.",
"You have 5 minutes to write a country song and perform it.",
 "Who is your favorite celebrity?",
"Do 5 minutes of stand-up comedy.",
 "Quack like a duck until your next turn.",
"Sing the national anthem in a British accent.",
    "What’s your most favorite meme?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Can you describe our friendship in three words?",
    "If you were a dog, which breed would you want to be?",
)

DARE = (
    "Show the most embarrassing photo on your phone"
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "propose someone here as a friend ",
    "Write Someones Name on paper of Here who is Online And Share it",
    "Write loveletter on book and share photo of that love letter .",
    "Select one song from and write lyrics of that song",
    "Say something dirty to the person on your leftYou've got company!",
    "Send Love letter to any one here",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Listen Song of dhinchak pooja with full volume on headphone ",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    "Suggest me more dares.",
)
